swagger:
  title: 'WindFlow PLM服务'
  prefix: /plm
mybatis-plus:
  mapper-locations: classpath*:cn/com/mfish/plm/mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    jdbc-type-for-null:
spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
          master:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://192.168.111.103:3306/mf_plm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
            username: root
            password: "!QAZ2wsx"