<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.com.mfish</groupId>
        <artifactId>mfish-nocode</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>mf-graph</artifactId>
    <packaging>pom</packaging>
    <name>mf-graph</name>
    <description>图数据库服务</description>

    <modules>
        <module>../mf-api/mf-graph-api</module>
        <module>../mf-business/mf-graph</module>
    </modules>
</project>
