mybatis-plus:
  mapper-locations: classpath*:cn/com/mfish/graph/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 1

spring:
  datasource:
    dynamic:
      primary: master
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 20
      datasource:
        master:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://192.168.111.103:5432/mf_plm
          username: postgres
          password: postgres
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.111.103:3306/mf_oauth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: "!QAZ2wsx"
rocketmq:
  consumer:
    nameServer: 192.168.111.103:9876
    group: plm-graph-sync-group
    topic: plm-graph-sync
    enableDLQ: true
    maxRetryTimes: 3

nebula:
  single:
    enabled: true
    addresses: 192.168.111.103:9669
  cluster:
    enabled: false
    addresses: []
  username: root
  password: nebula
  pool:
    min-conns: 10
    max-conns: 100
    timeout: 3000
    idle-timeout: 60
  space:
    name: plm_graph
    charset: utf8
    replica-factor: 1
    partition-num: 100
